apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: nginx
  name: nginx-deployment
  labels:
    app: nginx
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
    name: nginx-pod
    namespace: nginx
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx-cont
        image: nginx:1.14.2
        ports:
        - containerPort: 80



#  kubectl apply -f deployment.yaml --dry-run=client
#  kubectl apply -f deployment.yaml -n nginx
#  kubectl get deployments -n nginx
# kubectl get pods -n nginx
# kubectl scale deployment.yaml nginx-deployment -n nginx --replicas=5
##  kubectl set image deployment/nginx-deployment nginx-cont=nginx:1.14.2 -n nginx       
######   document https://kubernetes.io/docs/concepts/workloads/controllers/deployment/
