apiVersion: v1
kind: Pod
metadata: 
  name: nginx-pod     ###pod name
  namespace: nginx    ##namespace name
spec:
  containers: 
  - name: nginx-cont      ####container name
    image: nginx:1.14.2
    ports:
    - containerPort: 80


kubectl apply -f pod.yaml --dry-run=client       ####check file syntx OK
kubectl apply -f pod.yaml -n nginx               ###create pod
kubectl delete -f pod.yaml  -n nginx             ###delete the pods
